version: '3'
services:
  web:
    build: .
    command: iex -S mix phx.server
    container_name: make_word_bot
    volumes:
      - ./:/app
    ports:
      - "8443:8443"
    links:
      - db
    depends_on:
      - db
  test:
    build: .
    command: mix test
    environment:
      MIX_ENV: test
      PORT: 4001
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: make_word_bot_db
    ports:
      - '5432:5432'
    environment:
      ### Oooops, I've commited my database password =) TODO: let's think how to remove this later to env script
      POSTGRES_USER: nulleof
      POSTGRES_PASSWORD: b5XUHgAWnAn629hhza1XE687ccGQ61djudWq8N99Qj6VbfWCpsb4WCSU6336N27H